import { readdirSync, readFileSync, unlinkSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { PATHS, SCHEMA_VERSION } from "./constants.mjs";
import { copyTextIfMissing, ensureDir, exists, fingerprintPath, readJson, repoPath, sha256Buffer, writeJson, writeText } from "./fs.mjs";
import { scanRepository } from "./inventory.mjs";
import { fingerprintExcludes, fingerprintOptions, validateConfig } from "./policy.mjs";
import { navigatorIdentity, renderClaudeAgent, renderClaudeRule, renderMap, renderNavigatorBrief, slug } from "./render.mjs";

export function isInitialized(root) {
  return exists(repoPath(root, PATHS.config)) && exists(repoPath(root, PATHS.map));
}

export function loadState(root) {
  if (!isInitialized(root)) throw new Error("Mauro is not initialized. Run `mauro init`.");
  return {
    config: validateConfig(readJson(repoPath(root, PATHS.config))),
    map: readJson(repoPath(root, PATHS.map)),
    manifest: readJson(repoPath(root, PATHS.manifest)),
    fingerprints: readJson(repoPath(root, PATHS.fingerprints))
  };
}

function template(pluginRoot, name) {
  return join(pluginRoot, "templates", name);
}

function makeDocument(path, criticality, watches, knowledge = []) {
  return { path, status: "current", criticality, watches, knowledge };
}

function removeGeneratedView(root, path, prefix, requiredNamePrefix = "") {
  if (!path || !path.startsWith(`${prefix}/`) || !path.endsWith(".md")) return;
  const name = path.slice(path.lastIndexOf("/") + 1);
  if (requiredNamePrefix && !name.startsWith(requiredNamePrefix)) return;
  const absolute = repoPath(root, path);
  if (!exists(absolute)) return;
  const text = readFileSync(absolute, "utf8");
  if (!text.includes("Generated by Mauro")) return;
  unlinkSync(absolute);
}

function rebuildViews(root, map, previousManifest = null) {
  const preservedDocuments = Object.fromEntries(
    Object.entries(previousManifest?.documents || {}).filter(([id]) => id !== "doc-map" && id !== "doc-charter" && !id.startsWith("navigator-"))
  );
  const manifest = {
    schema_version: SCHEMA_VERSION,
    knowledge: previousManifest?.knowledge || {},
    documents: preservedDocuments,
    navigators: {}
  };
  const watchRoots = [...new Set(map.units.flatMap((unit) => unit.scope === "stub" ? (unit.manifests || [unit.manifest]).filter(Boolean) : [unit.root]))];
  manifest.documents["doc-map"] = makeDocument(PATHS.mapDocument, "informational", watchRoots);
  manifest.documents["doc-charter"] = previousManifest?.documents?.["doc-charter"] || makeDocument(PATHS.charter, "binding", []);

  writeText(repoPath(root, PATHS.mapDocument), renderMap(map));
  for (const capability of map.capabilities) {
    const identity = navigatorIdentity(capability);
    const capabilitySlug = slug(capability.id.replace(/^cap-/, ""));
    const source = `${PATHS.navigators}/${capabilitySlug}.md`;
    const agent = `${PATHS.agents}/${identity}.md`;
    const rule = `${PATHS.rules}/${capabilitySlug}.md`;
    writeText(repoPath(root, source), renderNavigatorBrief(capability));
    writeText(repoPath(root, agent), renderClaudeAgent(capability, source));
    writeText(repoPath(root, rule), renderClaudeRule(capability, source));
    manifest.navigators[identity] = {
      source,
      generated_agent: agent,
      generated_rule: rule,
      primary_paths: capability.primary_paths,
      secondary_paths: capability.secondary_paths,
      approved: capability.approved === true
    };
    manifest.documents[`navigator-${capabilitySlug}`] = makeDocument(
      source,
      "operational",
      capability.primary_paths.map((path) => path === "**" ? "." : path.replace(/\/\*\*$/, ""))
    );
  }
  for (const [identity, previous] of Object.entries(previousManifest?.navigators || {})) {
    if (manifest.navigators[identity]) continue;
    removeGeneratedView(root, previous.source, PATHS.navigators);
    removeGeneratedView(root, previous.generated_agent, PATHS.agents, "mauro-");
    removeGeneratedView(root, previous.generated_rule, PATHS.rules);
  }
  return manifest;
}

export function buildFingerprints(root, manifest, config, map) {
  const fingerprints = {
    schema_version: SCHEMA_VERSION,
    config_digest: sha256Buffer(Buffer.from(JSON.stringify(config))),
    records: {},
    documents: {}
  };
  for (const [id, record] of Object.entries(manifest.knowledge)) {
    fingerprints.records[id] = {};
    for (const path of record.paths || []) {
      fingerprints.records[id][path] = fingerprintPath(root, path, fingerprintExcludes(config, map, path), fingerprintOptions(config, map, root));
    }
  }
  for (const [id, document] of Object.entries(manifest.documents)) {
    fingerprints.documents[id] = {};
    for (const path of document.watches || []) {
      fingerprints.documents[id][path] = fingerprintPath(root, path, fingerprintExcludes(config, map, path), fingerprintOptions(config, map, root));
    }
  }
  return fingerprints;
}

export function initialize(root, pluginRoot) {
  if (isInitialized(root)) {
    throw new Error("Mauro is already initialized. Use `mauro map update`.");
  }
  const configPath = repoPath(root, PATHS.config);
  const config = validateConfig(exists(configPath) ? readJson(configPath) : readJson(template(pluginRoot, "config.json")));
  const map = scanRepository(root, config);
  for (const path of [PATHS.state, PATHS.docs, PATHS.knowledge, PATHS.navigators, PATHS.chronicles, PATHS.artifacts, PATHS.rules, PATHS.agents]) {
    ensureDir(repoPath(root, path));
  }
  copyTextIfMissing(template(pluginRoot, "config.json"), repoPath(root, PATHS.config));
  copyTextIfMissing(template(pluginRoot, "charter.md"), repoPath(root, PATHS.charter));
  writeJson(repoPath(root, PATHS.map), map);
  const manifest = rebuildViews(root, map);
  writeJson(repoPath(root, PATHS.manifest), manifest);
  const fingerprints = buildFingerprints(root, manifest, config, map);
  writeJson(repoPath(root, PATHS.fingerprints), fingerprints);
  writeJson(repoPath(root, PATHS.changes), { schema_version: 1, paths: [] });
  return { map, manifest, fingerprints };
}

export function updateMap(root) {
  const current = loadState(root);
  const scanned = scanRepository(root, current.config);
  const oldUnits = new Set(current.map.units.map((unit) => unit.id));
  const newUnits = new Set(scanned.units.map((unit) => unit.id));
  const addedUnits = scanned.units.filter((unit) => !oldUnits.has(unit.id));
  const removedUnits = current.map.units.filter((unit) => !newUnits.has(unit.id));
  const previousCapabilities = new Map(current.map.capabilities.map((item) => [item.id, item]));
  const capabilities = scanned.capabilities.map((capability) => {
    const previous = previousCapabilities.get(capability.id);
    if (!previous) return capability;
    return previous.provenance === "deterministic-draft" && previous.approved !== true
      ? capability
      : { ...capability, ...previous, id: capability.id };
  });
  const map = {
    ...scanned,
    capabilities,
    unresolved: [
      ...scanned.unresolved,
      ...addedUnits.map((unit) => ({ kind: "new-unit-needs-semantic-review", unit: unit.id, evidence: [unit.manifest || unit.root] })),
      ...removedUnits.map((unit) => ({ kind: "removed-unit-needs-semantic-review", unit: unit.id, evidence: [unit.manifest || unit.root] }))
    ]
  };
  writeJson(repoPath(root, PATHS.map), map);
  const manifest = rebuildViews(root, map, current.manifest);
  writeJson(repoPath(root, PATHS.manifest), manifest);
  const fresh = buildFingerprints(root, manifest, current.config, map);
  const policyChanged = current.fingerprints.config_digest !== fresh.config_digest;
  const fingerprints = {
    schema_version: SCHEMA_VERSION,
    config_digest: fresh.config_digest,
    records: current.fingerprints.records,
    documents: Object.fromEntries(Object.keys(manifest.documents).map((id) => [
      id,
      id === "doc-map" || !current.fingerprints.documents[id] || (policyChanged && id.startsWith("navigator-"))
        ? fresh.documents[id]
        : current.fingerprints.documents[id]
    ]))
  };
  writeJson(repoPath(root, PATHS.fingerprints), fingerprints);
  return { map, manifest, fingerprints };
}

export function readKnowledgeFiles(root) {
  const directory = repoPath(root, PATHS.knowledge);
  if (!exists(directory)) return [];
  return readdirSync(directory)
    .filter((name) => name.endsWith(".md"))
    .sort()
    .map((name) => ({ path: `${PATHS.knowledge}/${name}`, text: readFileSync(join(directory, name), "utf8") }));
}

export function pluginRootFrom(importMetaUrl) {
  return resolve(dirname(fileURLToPath(importMetaUrl)), "..");
}
